apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: prtoken
  name: prtoken
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prtoken
    spec:
      containers:
      - image: kevlar/prtoken:0.0
        name: prtoken
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
