apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/prtoken
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - prtoken-deployment.yaml
    - prtoken-service.yaml
    - roach-ui-claim0-persistentvolumeclaim.yaml
    - roach-ui-deployment.yaml
    - roach-ui-service.yaml
