apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: roach-ui
  name: roach-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: roach-ui
    spec:
      containers:
      - args:
        - start
        - --insecure
        image: cockroachdb/cockroach
        name: roach-ui
        ports:
        - containerPort: 26257
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /cockroach/cockroach-data
          name: roach-ui-claim0
      restartPolicy: Always
      volumes:
      - name: roach-ui-claim0
        persistentVolumeClaim:
          claimName: roach-ui-claim0
status: {}
